name: delta_markdown
version: 0.8.0

description: A library for converting between Markdown and Delta of the
  package flutter_quill.
homepage: https://github.com/friebetill/notus_markdown

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  charcode: ^1.3.1
  collection: ^1.18.0
  flutter_quill: 9.3.11

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.9
